USE blog;
INSERT INTO Article(firstUpdateDate,lastUpdateDate,title,articleBody,articleType,isDelete) VALUE("2023-5-11","2023-5-11","关于本站","关于本站","代码",'N');
INSERT INTO Article(firstUpdateDate,lastUpdateDate,title,articleBody,articleType,isDelete) VALUE("2023-5-11","2023-5-11","关于本站","关于本站","代码",'N');
INSERT INTO Article(firstUpdateDate,lastUpdateDate,title,articleBody,articleType,isDelete) VALUE("2023-5-11","2023-5-11","关于本站","关于本站","代码",'N');
INSERT INTO Article(firstUpdateDate,lastUpdateDate,title,articleBody,articleType,isDelete) VALUE("2023-5-11","2023-5-11","关于本站","关于本站","代码",'N');
INSERT INTO Article(firstUpdateDate,lastUpdateDate,title,articleBody,articleType,isDelete) VALUE("2023-5-11","2023-5-11","关于本站","关于本站","代码",'N');
INSERT INTO Article(firstUpdateDate,lastUpdateDate,title,articleBody,articleType,isDelete) VALUE("2023-5-11","2023-5-11","关于本站","关于本站","代码",'N');
INSERT INTO Article(firstUpdateDate,lastUpdateDate,title,articleBody,articleType,isDelete) VALUE("2023-5-11","2023-5-11","关于本站","关于本站","代码",'N');
INSERT INTO Article(firstUpdateDate,lastUpdateDate,title,articleBody,articleType,isDelete) VALUE("2023-5-11","2023-5-11","关于本站","关于本站","代码",'N');
INSERT INTO Article(firstUpdateDate,lastUpdateDate,title,articleBody,articleType,isDelete) VALUE("2023-5-11","2023-5-11","关于本站","关于本站","代码",'N');
INSERT INTO Article(firstUpdateDate,lastUpdateDate,title,articleBody,articleType,isDelete) VALUE("2023-5-11","2023-5-11","关于本站","关于本站","代码",'N');
